# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - refs/tags/{tagname}
    exclude:
      - refs/tags/{othertagname}

variables:
- group: my-vars

pool:
  vmImage: ubuntu-latest

parameters:
  - name: inputName
    displayName: Tell me your Name?
    type: string

steps: 
-  script: echo ${INPUTNAME}
   displayName: echo ${INPUTNAME}    
